---
# Main Ironic deployment playbook
# This playbook deploys all Ironic components.

- name: Deploy MariaDB
  ansible.builtin.import_playbook: mariadb-deploy.yml

- name: Deploy RabbitMQ
  ansible.builtin.import_playbook: rabbitmq-deploy.yml

- name: Deploy IPA Downloader
  ansible.builtin.import_playbook: ipa-deploy.yml

- name: Deploy Ironic API
  ansible.builtin.import_playbook: ironic-api-deploy.yml

- name: Deploy Ironic HTTP Server
  ansible.builtin.import_playbook: ironic-http-deploy.yml

- name: Deploy Ironic Conductor Template
  ansible.builtin.import_playbook: ironic-conductor-deploy.yml

- name: Wait for Services to Start
  hosts: localhost
  gather_facts: false
  become: true
  tasks:
    - name: Wait for MariaDB to be ready
      ansible.builtin.wait_for:
        port: "{{ mariadb_port }}"
        delay: 5
        timeout: 60
      ignore_errors: true

    - name: Wait for RabbitMQ to be ready
      ansible.builtin.wait_for:
        port: "{{ rabbitmq_amqp_port }}"
        delay: 5
        timeout: 60
      ignore_errors: true
