---
- name: Stop Ironic Services for Upgrade
  hosts: ironic
  become: true
  gather_facts: true
  tasks:
    - name: Stop conductor instances
      ansible.builtin.systemd:
        name: "ironic-conductor@{{ item.name }}"
        state: stopped
      loop: "{{ ironic_conductor_groups }}"
      loop_control:
        label: "{{ item.name }}"
      ignore_errors: true

    - name: Stop core services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
      loop:
        - ironic-api
        - ironic-http
      ignore_errors: true

- name: Upgrade Configuration and Schema
  hosts: ironic
  become: true
  gather_facts: true
  roles:
    - role: ironic_common

- name: Upgrade IPA Images
  hosts: ironic
  become: true
  gather_facts: true
  roles:
    - role: ipa_downloader

- name: Restart Ironic Services
  hosts: ironic
  become: true
  gather_facts: false
  roles:
    - role: ironic_http
    - role: ironic_api
    - role: ironic_conductor

- name: Refresh Containerized Ironic CLI Helper
  hosts: ironic
  become: true
  gather_facts: false
  roles:
    - role: ironic_cli

- name: Validate Upgrade
  ansible.builtin.import_playbook: validate.yml
